import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Chatbot } from '@/components/Chatbot'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hospital Management System',
    description: 'Generated by create next app',
}

import { Providers } from './providers'
import { SOSButton } from '@/components/SOSButton'

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <Providers>
                    {children}
                    <Chatbot />
                    <SOSButton />
                </Providers>
            </body>
        </html>
    )
}
