import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Chatbot } from '@/components/Chatbot'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hospital Management System',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <Chatbot />
            </body>
        </html>
    )
}
